# Generated by Django 4.2.30 on 2026-05-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_expected_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('payment_confirmed', 'Payment Confirmed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('return_requested', 'Return Requested'), ('returned', 'Returned')], db_index=True, default='pending', max_length=25),
        ),
    ]
