# Generated by Django 4.2.30 on 2026-05-18 22:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255, unique=True)),
                ('store_description', models.TextField(blank=True, default='')),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to='sellers/logos/')),
                ('store_banner', models.ImageField(blank=True, null=True, upload_to='sellers/banners/')),
                ('business_email', models.EmailField(blank=True, default='', max_length=254)),
                ('business_phone', models.CharField(blank=True, default='', max_length=15)),
                ('business_address', models.TextField(blank=True, default='')),
                ('gst_number', models.CharField(blank=True, default='', max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$', 'Enter a valid GST number.')])),
                ('pan_number', models.CharField(blank=True, default='', max_length=10)),
                ('bank_account_name', models.CharField(blank=True, default='', max_length=255)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=20)),
                ('bank_ifsc', models.CharField(blank=True, default='', max_length=11)),
                ('bank_name', models.CharField(blank=True, default='', max_length=255)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_sales', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
