# Generated by Django 4.2.30 on 2026-05-18 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=models.Index(fields=['is_verified'], name='sellers_sel_is_veri_d6c2b2_idx'),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=models.Index(fields=['verification_status'], name='sellers_sel_verific_dcfdcd_idx'),
        ),
    ]
