# Generated by Django 4.2.30 on 2026-05-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='products_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seller',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
