# Generated by Django 4.2.30 on 2026-05-18 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreservation',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stock_reservations', to='products.productvariant'),
        ),
    ]
