# Generated by Django 4.2.30 on 2026-05-18 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='reference_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to='orders.order'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inventory_logs', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='variant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.productvariant'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['variant', 'is_released'], name='inventory_s_variant_6ff4e6_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['expires_at', 'is_released'], name='inventory_s_expires_e2c318_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['variant', 'reason'], name='inventory_i_variant_9580ae_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['created_at'], name='inventory_i_created_108a29_idx'),
        ),
    ]
