# Generated by Django 4.2.30 on 2026-05-18 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
        ('orders', '0002_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerpayout',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payouts', to='sellers.seller'),
        ),
        migrations.AddField(
            model_name='refund',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='refund',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='refunds', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='payment', to='orders.order'),
        ),
    ]
